version: "3.8"

services:
  consumer:
    build:
      context: .
      dockerfile: docker/runtime/Dockerfile
    container_name: consumer
    networks:
      - market-net
    command: /workspace/apps/bin/consumer_main
    volumes:
       - .:/workspace

  producer:
    build:
      context: .
      dockerfile: docker/runtime/Dockerfile  # your existing producer Dockerfile
    container_name: producer
    depends_on:
      - consumer
    networks:
      - market-net
    working_dir: /workspace/apps/bin
    volumes:
      - .:/workspace
    command: >
      ./binance_main
      --config_file /workspace/apps/config/binance/config.json
      --key fut
      --symbol_file /workspace/apps/config/binance/symbols.json
      --zmqon

networks:
  market-net:

