services:
  consumer:
    build:
      context: .
      dockerfile: docker/runtime/Dockerfile
    container_name: consumer
    networks:
      - market-net
    command: /workspace/apps/bin/consumer_main --sendweb
    volumes:
      - .:/workspace

  producer:
    build:
      context: .
      dockerfile: docker/runtime/Dockerfile
    container_name: producer
    depends_on:
      - consumer
    networks:
      - market-net
    volumes:
      - .:/workspace
    command: /workspace/apps/bin/mock_producer_main

  webserver:
    build:
      context: ./server
      dockerfile: ../docker/webserver/Dockerfile
    container_name: fastapi-server
    networks:
      - market-net
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"  # Expose FastAPI to host for testing (optional)

networks:
  market-net:

