
services:
  consumer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.runtime
    container_name: consumer
    networks:
      - market-net
    command: /app/bin/consumer_main
    volumes:
       - ../data:/workspace/data:ro
       - ../apps/config:/workspace/apps/config:ro

  producer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.runtime
    container_name: producer
    depends_on:
      - consumer
    networks:
      - market-net
    volumes:
      - ../data:/workspace/data:ro
      - ../apps/config:/workspace/apps/config:ro
    command: >
      /app/bin/binance_main
      --config_file /workspace/apps/config/binance/config.json
      --key fut
      --symbol_file /workspace/apps/config/binance/symbols.json
      --zmqon

networks:
  market-net:

