[project]
name = "fastapi-server"
version = "0.1.0"
description = "FastAPI server for status messages"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic"
]

[tool.uv]
