name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build development image
      run: docker build -t cpp-crypto-dev -f docker/Dockerfile.dev .

    - name: Start development container
      run: |
        docker run -d --rm -v $PWD:/workspace --name cpp-crypto-dev-container cpp-crypto-dev sleep infinity
        docker ps

    - name: Verify Dependency Installation
      run: |
        echo "--- Verifying contents of /opt/cpp-crypto-deps/include ---"
        docker exec cpp-crypto-dev-container ls -l /opt/cpp-crypto-deps/include
        echo "--- Verifying contents of /opt/cpp-crypto-deps/lib ---"
        docker exec cpp-crypto-dev-container ls -l /opt/cpp-crypto-deps/lib

    - name: Build code
      run: |
        docker exec cpp-crypto-dev-container bash -x ./scripts/build/binance_build.sh
        docker exec cpp-crypto-dev-container bash -x ./scripts/build/consumer_build.sh

    - name: Run tests
      run: docker exec cpp-crypto-dev-container bash -c "cd /workspace && make test"
